FROM node:latest

WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install
RUN apt-get update && apt-get install -y libnss3 libdrm2 libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libgbm1 libxkbcommon0 libasound2

COPY . .

EXPOSE 3000
CMD ["node", "server.js"]
